// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA02Ce638oJceKEE4eY_hDl8EreT5Ph42U',
    appId: '1:50743563599:web:28074d4f003434e415e13a',
    messagingSenderId: '50743563599',
    projectId: 'stranger-mtf',
    authDomain: 'stranger-mtf.firebaseapp.com',
    storageBucket: 'stranger-mtf.firebasestorage.app',
    measurementId: 'G-61S68M393M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCieg9Ss6-9MPZtpJ18qjEun0zUD36aeGM',
    appId: '1:50743563599:android:44b41d773091827d15e13a',
    messagingSenderId: '50743563599',
    projectId: 'stranger-mtf',
    storageBucket: 'stranger-mtf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANFcjGLRwEdPRqDfb8fXS5pkdyxiMWi7U',
    appId: '1:50743563599:ios:28eabd5bfb946ea015e13a',
    messagingSenderId: '50743563599',
    projectId: 'stranger-mtf',
    storageBucket: 'stranger-mtf.firebasestorage.app',
    iosBundleId: 'com.example.stranger',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANFcjGLRwEdPRqDfb8fXS5pkdyxiMWi7U',
    appId: '1:50743563599:ios:28eabd5bfb946ea015e13a',
    messagingSenderId: '50743563599',
    projectId: 'stranger-mtf',
    storageBucket: 'stranger-mtf.firebasestorage.app',
    iosBundleId: 'com.example.stranger',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA02Ce638oJceKEE4eY_hDl8EreT5Ph42U',
    appId: '1:50743563599:web:45e376453f29ff5415e13a',
    messagingSenderId: '50743563599',
    projectId: 'stranger-mtf',
    authDomain: 'stranger-mtf.firebaseapp.com',
    storageBucket: 'stranger-mtf.firebasestorage.app',
    measurementId: 'G-EE8LTJW995',
  );
}
